app/__init__.py
from logger import c_logger as log
from app.application import create_app



log.info('Import app')

app/security/__init__.py
from app import log
from flask_security import Security, SQLAlchemySessionUserDatastore
from database import loadSession
from database import models


# it is needed to init security in application. fuck flask



def init_security(app):
    global user_datastore
    user_datastore = SQLAlchemySessionUserDatastore(loadSession(), models.UserAccount, models.UserRole)
    global security
    security = Security(app, user_datastore)
    user_datastore.remove_role_from_user(user='5@example.com', role='user')
    user_datastore.commit()

    log.info('Init security')

app/views/__init__.py
from app.views.api import api
from app.views.frontend import frontend
from app import log

log.info("Import views")

app/views/api.py
from flask import Flask, render_template, flash, redirect, url_for, Blueprint
from flask import request, jsonify, helpers, abort, session



api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/get_project_systems',
           methods=['GET'])  # Can return project list if no args and single project with project id
def get_hello():
    """return project systems by project_id"""

    return jsonify(result="Hello world")

app/views/frontend.py
from flask import Flask, render_template, flash, redirect, url_for, Blueprint
from flask import request, jsonify, helpers, session, after_this_request
from flask_security import login_required
from app.views import api
from flask import abort
from flask_login import current_user

from app.security import security, user_datastore
from database import loadSession
from database import models
from configuration import config as cf
from flask_security.utils import login_user, get_post_login_redirect

frontend = Blueprint('frontend', __name__)


@frontend.route('/')
@frontend.route('/index')
def index():
    return render_template("index.html", eth_wallet=cf.ACCOUNT_ADDRESS)


@frontend.route('/organisation')
@login_required
def organisation():
    return render_template("organisation.html", eth_wallet=cf.ACCOUNT_ADDRESS)


@frontend.route('/user_dashboard')
@login_required
def user_dashboard():
    session = loadSession()
    if (not current_user.is_authenticated):
        abort(500)

    user_id = current_user.id
    documents = session.query(models.NationalDocument).filter_by(user_id=user_id).all()
    certificates = []
    for doc in documents:
        certificates.extend(session.query(models.Certificate).filter_by(personal_document_id=doc.document_number,
                                                                        personal_document_type_code=doc.document_type_code).all())
    for cert in certificates:
        cert.org_name = session.query(models.Organisation).filter_by(
            ethereum_wallet=cert.organisation_ethereum_wallet).first().name

    return render_template("user_dashboard.html", certificates=certificates)

app/templates/base.html
<!DOCTYPE html>


<html lang="en">

<head>
    {% block head %}
        <meta charset="UTF-8">
        {% block css %}

            <!-- Bootstrap Core CSS -->
            <link href="{{ url_for('static', filename='lib/bootstrap/css/bootstrap.min.css' ) }}" rel="stylesheet">

            <!-- MetisMenu CSS -->
            <link href="{{ url_for('static', filename='lib/metisMenu/metisMenu.min.css' ) }}" rel="stylesheet">



            <!-- Custom CSS -->
            <link href="{{ url_for('static', filename='lib/sb-admin/css/sb-admin-2.css' ) }}" rel="stylesheet">

            {#    <!-- Morris Charts CSS -->#}
            {#    <link href="{{ url_for('static', filename='lib/morrisjs/morris.css' )}}" rel="stylesheet">#}

            <!-- Custom Fonts -->
            <link href="{{ url_for('static', filename='lib/font-awesome/css/fontawesome-all.css' ) }}"
                  rel="stylesheet">

        {% endblock %}
        <title>{% block title %}{% endblock %}</title>
        </head>
        <body>
        <div id="wrapper">
        {% block top_navbar %}
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('frontend.index') }}"><i class="fa fa-crow fa-fw"></i>
                        EduCerts</a>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">

                    {% if current_user.is_authenticated %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="#">
                                        <div>
                                            <i class="fa fa-comment fa-fw"></i> New Comment
                                            <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <div>
                                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                            <span class="pull-right text-muted small">12 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                                            <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <div>
                                            <i class="fa fa-tasks fa-fw"></i> New Task
                                            <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <div>
                                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                            <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a class="text-center" href="#">
                                        <strong>See All Alerts</strong>
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </li>
                            </ul>
                            <!-- /.dropdown-alerts -->
                        </li>
                        <!-- /.dropdown -->
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                                </li>
                                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('security.logout') }}"><i class="fa fa-sign-out fa-fw"></i>
                                    Logout</a>
                                </li>
                            </ul>
                            <!-- /.dropdown-user -->
                        </li>
                        <!-- /.dropdown -->

                    {% endif %}

                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="{{ url_for('frontend.index') }}"><i class="fa fa-crow fa-fw"></i>Index</a>
                            </li>
                            {% if not current_user.is_authenticated %}
                                {% include "security/_menu.html" %}
                            {% else %}

                                <li>
                                    <a href="{{ url_for('frontend.user_dashboard') }}"><i class="fa fa-dochub fa-fw"></i> My certificates</a>
                                    <!-- /.nav-second-level -->
                                </li>
                                <li>
                                    <a href="{{ url_for('frontend.organisation') }}"><i class="fa fa-table fa-fw"></i>
                                        Organisation</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>


        {% endblock %}
    {% endblock %}

    <div id="page-wrapper" >
        {% block content %}{% endblock %}
    </div>

    <!--Footer-->
        <footer class="footer">
            <div class="container">
                <span class="text-muted"> © 2018 Copyright: Nikita Kosov</span>
                <!--/Copyright-->
            </div>
        </footer>
    <!--/Footer-->

    </div>
    {% block scripts %}


        <!-- jQuery -->
        <script src="{{ url_for('static', filename='lib/jquery/jquery.js' ) }}"></script>


        <!-- Bootstrap Core JavaScript -->
        <script src="{{ url_for('static', filename='lib/bootstrap/js/bootstrap.min.js' ) }}"></script>


        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ url_for('static', filename='lib/metisMenu/metisMenu.min.js' ) }}"></script>


        {#    <!-- Morris Charts JavaScript -->#}
        {##}
        {#    <script src="{{ url_for('static', filename='lib/raphael/raphael.min.js' )}}"></script>#}
        {#    <script src="{{ url_for('static', filename='lib/morrisjs/morris.min.js' )}}"></script>#}
        {#    <script src="{{ url_for('static', filename='lib/sb-admin/morris-data.js' )}}"></script>#}

                <script type="text/javascript"
            src="{{ url_for('static', filename='lib/datatables/js/jquery.dataTables.js' ) }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='lib/datatables-plugins/dataTables.bootstrap.js' ) }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='lib/datatables-responsive/dataTables.responsive.js' ) }}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{{ url_for('static', filename='lib/sb-admin/js/sb-admin-2.js' ) }}"></script>
    {% endblock %}
    </body>
</html>

app/templates/index.html
{% extends "./base.html" %}
{% block title %}Index{% endblock %}
{% block content %}


    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Greetings</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><strong>Greetings</strong></h4>
                </div>
                <div class="panel-body">
                    Technically, Blockchain is a distributed database, spread across many computers with no central
                    control
                    that
                    could transform governance, the economy, businesses and the functioning of organisations. And by the
                    way, it’s
                    already here, not only in Bitcoin, but in many other services and commodities – badges, credits, and
                    qualifications.
                    Each ‘block’ is transparent but tamper-proof. A ‘block’ has a timestamp for recording transactions
                    and
                    offers
                    indelible proof of all of them. Rather than relying on third parties, it’s a frictionless method for
                    transacting
                    with others.
                    In normal speak, the basic idea is that you cut out the middleman. There is no central database as
                    everything is
                    distributed, public, synchronised and encrypted. All transactions are logged with a time, date and
                    other
                    details
                    – then verified by some very smart maths. Consensus decides, and every transaction is public.
                    What this promises is a more efficient, secure and transparent way of handling transactions. This
                    could
                    save a
                    huge amount of administration, bureaurocracy, effort and time. The Internet of things may release
                    its
                    potential.
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><strong>Who can use it?</strong></h4>
                </div>
                <div class="panel-body">
                    Blockchain can be implemented within individual educational institutions, groups of educational
                    institutions,
                    and both national and international educational bodies. In fact anyone wanting to securely store
                    badges,
                    credits, and qualifications – and make educational data that matters available to others – could
                    consider using
                    blockchain technology.
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </div>

{% endblock %}

app/templates/organisation.html
{% extends "./base.html" %}
{% block title %}Organisation{% endblock %}
{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/ethereum.js' ) }}"></script>
    <div class="col-md-6 col-sm-12" style="max-width: 640px;">
        <label class="hidden" id="ethereum_wallet">{{ eth_wallet }}</label>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Load certificate</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="cert-file">Certificate JSON file</label>
                <input type="file" id="cert-file" aria-describedby="emailHelp"
                       placeholder="Enter email">
                <small id="file-help" class="form-text text-muted">File shall be correctly formatted.</small>
            </div>

            <div class="progress-bar progress-bar-info" role="progressbar" id="file-upload-progress-bar"
                 aria-valuenow="0"
                 aria-valuemin="0"
                 aria-valuemax="100" style="width: 0; opacity: 100%">
                <span class="sr-only">20% Complete</span>
            </div>

        </div>
        <div class="col-md-12">
            <button id="send_json" type="button" class="btn btn-primary">Load</button>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="web3_error_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-danger" id="myModalLabel">Error</h4>
                </div>
                <div class="modal-body">
                    Looks like there is no Web3 provider in your browser. Please, install one, or use Web3 browser
                    (Mist).

                    I suggest Metamask:
                    <a target="_blank" href="https://metamask.io/">
                        <img src="{{ url_for('static', filename='assets/download-metamask-dark.png') }}"
                             alt="download metamask button dark" style="max-width:30%;">
                    </a>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
{% endblock %}

app/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
    <p>
        {{ field.label }} {{ field(**kwargs)|safe }}
        {% if field.errors %}

                {% for error in field.errors %}

                    <div class="alert alert-danger alert-dismissable" role="alert">
                        <button class="close" aria-hidden="true" type="button" data-dismiss="alert">×</button>
                        {{ error }}

                    </div>
                {% endfor %}
            {% endif %}

    </p>
{% endmacro %}

{% macro render_field(field) %}
    <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

app/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}

  <li> <a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}"><i class="fa fa-sign-in-alt fa-fw"></i> {{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}"><i class="fa fa-edit fa-fw"></i> {{ _('Register') }}</a></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}"><i class="fa fa-bar-chart-o fa-fw"></i> {{ _('Forgot password') }}</a></li>
  {% endif %}
  {% if security.confirmable %}
  <li> <a href="{{ url_for_security('send_confirmation') }}"><i class="fa fa-bar-chart-o fa-fw"></i>{{ _('Confirm account') }}</a></li>
  {% endif %}

{% endif %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
    {% if messages %}

            {% for category, message in messages %}
        <div class="alert alert-danger alert-dismissable" role="alert">
            <button class="close" aria-hidden="true" type="button" data-dismiss="alert">×</button>
            {{ message }}
        </div>
            {% endfor %}


    {% endif %}
{%- endwith %}

app/templates/security/change_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Change password') }}</h1>
<form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
  {{ change_password_form.hidden_tag() }}
  {{ render_field_with_errors(change_password_form.password) }}
  {{ render_field_with_errors(change_password_form.new_password) }}
  {{ render_field_with_errors(change_password_form.new_password_confirm) }}
  {{ render_field(change_password_form.submit) }}
</form>

app/templates/security/forgot_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Send password reset instructions') }}</h1>
<form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ render_field_with_errors(forgot_password_form.email) }} 
  {{ render_field(forgot_password_form.submit) }}
</form>
{% include "security/_menu.html" %}

app/templates/security/login_user.html
{% extends "./base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block title %}
{{ _('Login') }}
{% endblock %}
{% block content %}


    <div class="container" style="max-width: 640px;">
        <h1>{{ _('Login') }}</h1>
        {% include "security/_messages.html" %}
        <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
            {{ login_user_form.hidden_tag() }}
            {{ render_field_with_errors(login_user_form.email, class="form-control") }}
            {{ render_field_with_errors(login_user_form.password, class="form-control") }}

            {{ render_field_with_errors(login_user_form.remember) }}

            {{ render_field(login_user_form.next) }}
            {{ render_field(login_user_form.submit, class='btn btn-primary') }}
        </form>
    </div>

{% endblock %}

app/templates/security/register_user.html
{% extends "./base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
{% block title %}
{{ _('Register') }}
{% endblock %}

{% block content %}
<div class="container" style="max-width: 640px;">
<h1>{{ _('Register') }}</h1>
    <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
        {{ register_user_form.hidden_tag() }}
        {{ render_field_with_errors(register_user_form.email, class="form-control") }}
        {{ render_field_with_errors(register_user_form.password, class="form-control") }}
        {% if register_user_form.password_confirm %}
            {{ render_field_with_errors(register_user_form.password_confirm, class="form-control") }}
        {% endif %}
        {{ render_field(register_user_form.submit, class='btn btn-primary') }}

    </form>
</div>
{% endblock %}

app/templates/user_dashboard.html
{% extends "./base.html" %}
{% block title %}Organisation{% endblock %}
{% block content %}

                <link href="{{ url_for('static', filename='lib/datatables-plugins/dataTables.bootstrap.css' ) }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/datatables-responsive/dataTables.responsive.css' ) }}" rel="stylesheet">



    <div class="col-md-6 col-sm-12" style="max-width: 640px;">

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">My certificates</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <table class="table table-striped table-bordered table-hover" id="certificate-table"  style="width:100%">
                <thead>
                <tr>
                    <th>Course</th>
                    <th>Organisation</th>
                    <th>Course length</th>
                    <th>Certificate type</th>
                    <th>Start date</th>
                    <th>End date</th>
                </tr>
                </thead>
                <tbody>
                {% if certificates|count == 0 %}
                    <tr>
                        <td colspan="6">No certificates found. Enter correct document id.</td>
                    </tr>
                {% else %}
                    {% for cert in certificates %}
                        <tr>
                            <th>{{ cert.course_name }}</th>
                            <th>{{ cert.org_name }}</th>
                            <th>{{ cert.course_length }}</th>
                            <th>{{ cert.certificate_type_code }}</th>
                            <th>{{ cert.course_start_date }}</th>
                            <th>{{ cert.course_end_date }}</th>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/user_dashboard.js' ) }}"></script>

{% endblock %}